Create timi.md
NotANameServer/challenges pull request #52
Opened 2021-08-10 16:52 UTC by Meithal

Proposition protocole

2021-08-10 17:18 UTC, Meithal commented
+ commande replay

2021-08-20 13:29 UTC, Equinox4 requested changes
Hello, j'ai fais une petite review de ta proposition de protocole pour le Puissance 4.
Tout d'abord, merci d'avoir pris le temps de rédiger tout ça, c'est super cool :)
J'ai commenté quelques points qui me semble avoir besoin d'une clarification.
De plus, j'ai pas trop compris cette histoire de super utilisateur, je suppose qu'il s'agit du serveur, mais ça mériterait un petit paragraphe dédié imo.

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +Il passe via des messages publics (par exemple PRIVMSG),
clarifier cette phrase
"Il passe" ?
"messages publics" -> "PRIVMSG" ?

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +sans nécessiter de modifier les protocoles en question.
de quels protocoles parle-t-on ?
ce texte défini lui-même un protocole

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> + `PRIVMSG #salon1 play 4`
je ne comprends pas, la commande que le client envoie, c'est answer-play ou PRIVMSG ?
d'ou vient play ?

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> + `PRIVMSG #salon1 play tata 15`
je ne comprends pas, la commande que le serveur broadcast c'est command-task-play ou PRIVMSG ?
d'ou vient play ?

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +pour jouer à la quatrième colonne. La numérotation commence
*La numérotation des colonnes
+ préciser si on part de la gauche ou de la droite

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +`command-task-play` comprennant le joueur suivant.
pakompri

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +PRIVMSG #salon1 end le joueur 1 a été déconnecté
que vient faire PRIVMSG ici ?
c'est pas un message privé vu que c'est broadcast par le serveur

2021-08-20 13:29 UTC, Equinox4 commented on defi09/timi.md
> +C'est aux clients de détecter qui a gagné mais le super
"C'est aux clients de détecter qui a gagné" huh oO ?
et en cas de conflit, si un client dit qu'il a gagné, mais que l'autre est pas d'accord, on fait comment ?

2021-08-22 05:22 UTC, Meithal commented
Je reprend toutes les remarques en une fois

> "messages publics" -> "PRIVMSG"
Privmsg est la commande qui permet d'envoyer des messages publics sur IRC, je t'invite à lire la RFC
Sinon les exemples sont plutot du pseudocode que du vrai IRC, mais ils gagneraient à être corrigés.

> je ne comprends pas, la commande que le client envoie, c'est answer-play ou PRIVMSG ?
Si ce n'est pas clair pour quelqu'un d'autre je pense que le plus simple d'enlever tous les exemples.

> c'est pas un message privé vu que c'est broadcast par le serveur
Idem.

>et en cas de conflit, si un client dit qu'il a gagné, mais que l'autre est pas d'accord, on fait comment ?
Les deux seront gagnants.

Je vais essayer de modifier le document pour le rendre plus clair

2021-08-22 08:37 UTC, Mesteery commented
> Un super utilisateur est un utilisateur qui a la possibilité de créer des canaux, il est aussi celui qui dit à qui c'est de jouer. Il faudrait peut être utiliser un autre mot comme "arbitre" ?

Pourquoi ce serait pas le serveur ?

> Ici ce sont les protocoles IRC ou discord, sur lequel notre propre protocole s'appuie.

IRC et Discord sont beaucoup trop différent, donc tu peux pas laisser tant de liberté pour le choix du protocole sur lequelle se base ce protocole. *Bonne chance pour faire jouer une IA sur Discord.*

> Les deux auront gagné.

C'est pas bon ça, c'est au serveur de gérer et d'en annoncer un.

2021-08-22 19:36 UTC, Meithal commented
> Pourquoi ce serait pas le serveur ?

Car il n'y a pas vraiment besoin d'avoir accès au serveur, surtout que c'est impossible avec discord

> Bonne chance pour faire jouer une IA sur Discord

Comment ca ?

> C'est pas bon ça, c'est au serveur de gérer et d'en annoncer un.

Ok, pourquoi pas

2021-08-23 02:05 UTC, Equinox4 reviewed
Quelques fautes d'ortho à corriger + mon retour sur les précédents commentaire:
> Privmsg est la commande qui permet d'envoyer des messages publics sur IRC, je t'invite à lire la RFC

Je connais la RFC, PRIVMSG sert à envoyer un message privé à des utilisateurs.
Même si on peut envoyer un message à un/des channels entier, les utilisateurs qui ne sont pas inclus ne le recevront pas, ce n'est donc pas public.
Mais bon, le point de ma remarque c'est surtout le nommage, si tu veux faire une commande qui envoie des messages publics, tu la nomme pas "privmsg", ou alors, il ne faut pas appeler ça un message public et dire qu'on l'envoie dans le channel dans lequel se trouve les joueurs pour la partie en cours.

> Les deux auront gagné.

Ce n'est pas acceptable, dans ce jeu, on peut avoir des matchs nuls, mais en aucun cas deux gagnants (ni deux perdants).

2021-08-23 02:05 UTC, Equinox4 commented on defi09/timi.md
> +Il utile des messages publics (par exemple PRIVMSG),
*utilise ?

2021-08-23 02:05 UTC, Equinox4 commented on defi09/timi.md
> +la partie commence et le'arbitre envoie un broadcast
l'arbitre

2021-08-30 09:15 UTC, Equinox4 approved these changes

2021-08-30 09:18 UTC, Mesteery approved these changes

2021-08-30 09:18 UTC, merged